"""Armature analytics helpers for Python MCP servers."""

from .emit import IngestRejectedError, post_telemetry_event
from .events import (
    build_actor_id,
    build_actor_identity_event,
    build_event_id,
    build_session_init_event,
    build_tool_call_event,
    finalize_tool_call_event,
    normalize_session_id,
)
from .recorder import AnalyticsRecorder, create_analytics_recorder
from .sanitize import (
    BASE64_REMOVED_PLACEHOLDER,
    BINARY_REMOVED_PLACEHOLDER,
    REDACTION_FAILED_PLACEHOLDER,
    prepare_for_preview,
    SANITIZATION_BUDGET,
    sanitize_value,
)
from .queue import (
    PRIVACY_QUEUE_BATCH_SIZE,
    PRIVACY_QUEUE_CAPACITY,
    PrivacyQueue,
    create_privacy_queue,
)
from .redact_secrets import (
    SECRET_PATTERN_RULES,
    SENSITIVE_FIELD_NAMES,
    normalize_sensitive_field_name,
    redact_secrets_in_string,
    redact_secrets_in_value,
)
from .schema import (
    ToolTelemetryPlan,
    append_telemetry_hint,
    apply_telemetry_field_map,
    create_telemetry_json_schema,
    decorate_input_schema_with_telemetry,
    extract_telemetry_arguments,
    is_capture_enabled,
    normalize_telemetry_args,
    plan_tool_telemetry,
    schema_declares_telemetry,
)
from .server import FastMCPInstrumentation, instrument_fastmcp, with_mcp_analytics
from .stateless_http import (
    StatelessHttpSession,
    StatelessHttpSessionMiddleware,
    build_stateless_session_id,
    parse_stateless_session_client_info,
    resolve_stateless_http_session,
)
from .types import (
    ActorIdentifierResolver,
    AnalyticsConfig,
    AnalyticsIngestBatch,
    AnalyticsIngestEvent,
    McpClientInfo,
    RedactFunction,
    RedactableToolCall,
    RedactEventHook,
    TelemetryArgs,
    TelemetryFieldMap,
    TelemetryMode,
)

__all__ = [
    "ActorIdentifierResolver",
    "AnalyticsConfig",
    "AnalyticsIngestBatch",
    "AnalyticsIngestEvent",
    "AnalyticsRecorder",
    "BASE64_REMOVED_PLACEHOLDER",
    "BINARY_REMOVED_PLACEHOLDER",
    "FastMCPInstrumentation",
    "IngestRejectedError",
    "McpClientInfo",
    "PRIVACY_QUEUE_BATCH_SIZE",
    "PRIVACY_QUEUE_CAPACITY",
    "PrivacyQueue",
    "REDACTION_FAILED_PLACEHOLDER",
    "RedactableToolCall",
    "RedactEventHook",
    "RedactFunction",
    "SANITIZATION_BUDGET",
    "SECRET_PATTERN_RULES",
    "SENSITIVE_FIELD_NAMES",
    "StatelessHttpSession",
    "StatelessHttpSessionMiddleware",
    "TelemetryArgs",
    "TelemetryFieldMap",
    "TelemetryMode",
    "ToolTelemetryPlan",
    "append_telemetry_hint",
    "apply_telemetry_field_map",
    "build_actor_id",
    "build_actor_identity_event",
    "build_event_id",
    "build_session_init_event",
    "build_stateless_session_id",
    "build_tool_call_event",
    "create_analytics_recorder",
    "create_privacy_queue",
    "create_telemetry_json_schema",
    "decorate_input_schema_with_telemetry",
    "extract_telemetry_arguments",
    "instrument_fastmcp",
    "is_capture_enabled",
    "normalize_session_id",
    "normalize_sensitive_field_name",
    "normalize_telemetry_args",
    "plan_tool_telemetry",
    "post_telemetry_event",
    "parse_stateless_session_client_info",
    "prepare_for_preview",
    "redact_secrets_in_string",
    "redact_secrets_in_value",
    "resolve_stateless_http_session",
    "sanitize_value",
    "schema_declares_telemetry",
    "with_mcp_analytics",
]
